<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_ErrorMessage</name>
   <tag></tag>
   <elementGuidId>00ec010e-dc8f-49df-bd28-21011e779ed2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test=&quot;error&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-test = 'error']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-test = 'error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>891325c2-4c46-4eda-ab05-9293a549f476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>error</value>
      <webElementGuid>c495aa78-ac47-4633-9216-181fd3ca447f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Epic sadface: Username is required</value>
      <webElementGuid>c53da37a-03bf-405e-9a4c-9160867774ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-572bbb4624b9f391499cff5f709e853a</value>
      <webElementGuid>85d9bfbf-5597-4e2c-9118-1e03fed3d37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-test = 'error']</value>
      <webElementGuid>9dfc97de-78f2-46ed-a06a-40087c41d91e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-test = 'error']</value>
      <webElementGuid>0de83f67-c8d5-4d47-9839-6f4b32ab7e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Epic sadface: Username is required' or . = 'Epic sadface: Username is required')]</value>
      <webElementGuid>b0d61963-1a5b-4314-af1a-0ed2678f376b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
