<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Sort</name>
   <tag></tag>
   <elementGuidId>2c35bd80-90f5-4a62-ba84-81223d1f43e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[data-test=&quot;secondary-header&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-test = 'product-sort-container']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-test='product-sort-container']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>product-sort-container</value>
      <webElementGuid>cbb07f19-5e4e-4638-9bf6-b57cc803384e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ProductsName (A to Z)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)' or . = 'ProductsName (A to Z)Name (A to Z)Name (Z to A)Price (low to high)Price (high to low)')]</value>
      <webElementGuid>4301d956-a653-4fff-96c6-f05571351772</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
